Repository Activiti/activiti-cloud-notifications-service-graphql, pull requests merged in 2019-02, with the labels that each got.

#10 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions
  pom.xml
Labels: updatebot

#11 Fix Cloud Build Dependency Management Priority
  Dockerfile
  charts/activiti-cloud-notifications-service-graphql/.helmignore
  charts/activiti-cloud-notifications-service-graphql/Chart.yaml
  charts/activiti-cloud-notifications-service-graphql/Makefile
  charts/activiti-cloud-notifications-service-graphql/README.md
  charts/activiti-cloud-notifications-service-graphql/templates/NOTES.txt
  charts/activiti-cloud-notifications-service-graphql/templates/_helpers.tpl
  charts/activiti-cloud-notifications-service-graphql/templates/deployment.yaml
  charts/activiti-cloud-notifications-service-graphql/templates/service.yaml
  charts/activiti-cloud-notifications-service-graphql/values.yaml
  charts/preview/Chart.yaml
  charts/preview/Makefile
  charts/preview/requirements.yaml
  charts/preview/values.yaml
  dependencies/pom.xml
  pom.xml
  skaffold.yaml
  watch.sh
Labels: bug

#12 fix: (GraphiQL) move to /graphiql
  services/graphiql/src/main/java/org/activiti/cloud/services/notifications/graphql/graphiql/GraphiQLConfigController.java
  services/graphiql/src/main/java/org/activiti/cloud/services/notifications/graphql/graphiql/GraphiQLIndexController.java
  services/graphiql/src/main/java/org/activiti/cloud/services/notifications/graphql/graphiql/KeycloakJsonController.java
  services/graphiql/src/main/resources/static/graphiql/graphiql.css
  services/graphiql/src/main/resources/static/graphiql/graphiql.html
  services/graphiql/src/main/resources/static/graphiql/graphiql.js
  services/graphiql/src/main/resources/static/graphiql/vendor/cdn.jsdelivr.net/es6-promise/4.0.5/es6-promise.auto.min.js
  services/graphiql/src/main/resources/static/graphiql/vendor/cdn.jsdelivr.net/fetch/0.9.0/fetch.min.js
  services/graphiql/src/main/resources/static/graphiql/vendor/cdn.jsdelivr.net/react/15.4.2/react-dom.min.js
  services/graphiql/src/main/resources/static/graphiql/vendor/cdn.jsdelivr.net/react/15.4.2/react.min.js
  services/graphiql/src/main/resources/static/graphiql/vendor/keycloak/auth/js/keycloak.js
  services/graphiql/src/main/resources/static/graphiql/vendor/unpkg.com/graphiql-subscriptions-fetcher@0.0.2/browser/client.js
  services/graphiql/src/main/resources/static/graphiql/vendor/unpkg.com/subscriptions-transport-ws@0.8.3/browser/client.js
Labels: enhancement

#13 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions
  pom.xml
Labels: updatebot

#14 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions
  pom.xml
Labels: updatebot

#15 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions
  pom.xml
Labels: updatebot

#16 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions
  pom.xml
Labels: updatebot

#17 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions
  pom.xml
Labels: updatebot

#19 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions
  pom.xml
Labels: updatebot

#20 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions
  pom.xml
Labels: updatebot

#22 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions
  pom.xml
Labels: updatebot

#23 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions
  pom.xml
Labels: updatebot

#25 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions
  pom.xml
Labels: updatebot

#21 feat: add servlet context path support for notifications service
  services/graphiql/src/main/java/org/activiti/cloud/services/notifications/graphql/graphiql/GraphiQLConfigController.java
  services/graphiql/src/test/java/org/activiti/cloud/services/notifications/graphql/graphiql/GraphiQLAutoConfigurationTest.java
  services/graphiql/src/test/resources/application.properties
Labels: enhancement

#26 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions
  pom.xml
Labels: updatebot

#27 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions
  pom.xml
Labels: updatebot

#28 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions
  pom.xml
Labels: updatebot
