Repository Activiti/activiti-cloud-notifications-service-graphql, pull requests merged in 2019-12, with the labels that each got.

#192 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot

#193 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot

#194 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot

#195 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot

#196 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot

#197 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot

#198 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot

#199 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot

#200 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot

#201 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot

#202 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot

#203 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot

#204 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot

#205 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot

#206 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot

#207 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot

#208 fix(AAE-973): Removed StompBrokerRelay dependency on RabbitMq
  services/ws/src/main/java/org/activiti/cloud/services/notifications/graphql/ws/config/GraphQLWebSocketMessageBrokerAutoConfiguration.java
Labels: bug

#209 refactor: Share one engine event processor stream to many subscribers
  services/events/src/main/java/org/activiti/cloud/services/notifications/graphql/events/consumer/EngineEventsConsumerAutoConfiguration.java
  services/subscriptions/src/main/java/org/activiti/cloud/services/notifications/graphql/subscriptions/datafetcher/EngineEventsFluxPublisherFactory.java
Labels: enhancement

#210 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot

#211 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot

#212 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot

#213 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot

#214 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot

#215 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot

#216 fix(versions): update Activiti/activiti-cloud-notifications-service-graphql versions into develop
  pom.xml
Labels: updatebot
